/**
 * DepthPanel — synthetic market depth (DOM) for the active symbol.
 *
 * Display-only: the ladder is generated by the deterministic depth engine
 * (src/engine/depth.ts) from the same frozen constants as the price path.
 * It never participates in fills or validation.
 */
import { depthAt } from "@/engine/depth";
import { formatINR } from "@/lib/format";
import { cn } from "@/lib/utils";
import { useMemo } from "react";
import { ArrowDownNarrowWide } from "lucide-react";

interface DepthPanelProps {
  symbol: string;
  nowSec: number;
  className?: string;
}

const MAX_BAR = 320; // max synthetic qty for width normalization

function SideRows({
  rows,
  color,
  align,
}: {
  rows: { pricePaise: bigint; qty: number; orders: number }[];
  color: "up" | "down";
  align: "left" | "right";
}) {
  const maxQty = Math.max(MAX_BAR, ...rows.map((r) => r.qty));
  return (
    <div className="flex flex-col gap-px">
      {rows.map((r, i) => (
        <div
          key={i}
          className={cn(
            "relative flex items-center justify-between overflow-hidden rounded px-2 py-1",
            align === "right" && "flex-row-reverse",
          )}
        >
          <div
            aria-hidden
            className={cn("absolute inset-y-0 opacity-15", color === "up" ? "bg-up" : "bg-down", align === "left" ? "left-0" : "right-0")}
            style={{ width: `${Math.min(100, (r.qty / maxQty) * 100)}%` }}
          />
          <span
            className={cn(
              "tnum relative font-mono text-[12px] font-semibold",
              color === "up" ? "text-up" : "text-down",
            )}
          >
            {formatINR(r.pricePaise)}
          </span>
          <span className="tnum relative text-right font-mono text-[12px] text-foreground/90">
            {r.qty}
          </span>
          <span className="tnum relative text-right font-mono text-[10px] text-muted-foreground">
            {r.orders}
          </span>
        </div>
      ))}
    </div>
  );
}

export function DepthPanel({ symbol, nowSec, className }: DepthPanelProps) {
  const depth = useMemo(() => depthAt(symbol, nowSec), [symbol, nowSec]);

  const totalBid = depth.bids.reduce((s, r) => s + r.qty, 0);
  const totalAsk = depth.asks.reduce((s, r) => s + r.qty, 0);
  const imbalance = totalBid + totalAsk === 0 ? 50 : Math.round((totalBid / (totalBid + totalAsk)) * 100);

  return (
    <div className={cn("flex flex-col", className)}>
      <div className="flex items-center justify-between px-4 pt-3 pb-2">
        <h3 className="flex items-center gap-1.5 text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
          <ArrowDownNarrowWide className="size-3.5" />
          Market depth
        </h3>
        <span className="font-mono text-[10px] text-muted-foreground">
          {symbol}
        </span>
      </div>

      {/* column headers */}
      <div className="grid grid-cols-[1fr_auto_auto] gap-x-3 px-2 pb-1 text-[9px] font-semibold tracking-wider text-muted-foreground uppercase">
        <span className="pl-2">Price</span>
        <span className="text-right">Qty</span>
        <span className="w-7 text-right">Ord</span>
      </div>

      {/* asks: deepest first so best ask sits adjacent to the spread row */}
      <div className="px-2">
        <SideRows rows={[...depth.asks].reverse()} color="down" align="right" />
      </div>

      {/* spread bar */}
      <div className="my-1 flex items-center justify-between border-y border-border bg-muted/30 px-3 py-1">
        <span className="text-[10px] font-semibold tracking-wider text-muted-foreground uppercase">
          Spread
        </span>
        <span className="tnum font-mono text-[11px] font-semibold text-gold">
          {formatINR(depth.asks[0].pricePaise - depth.bids[0].pricePaise)}
        </span>
      </div>

      {/* bids: best first */}
      <div className="px-2">
        <SideRows rows={depth.bids} color="up" align="left" />
      </div>

      {/* buy/sell pressure bar */}
      <div className="mt-2 px-4 pb-3">
        <div className="mb-1 flex items-center justify-between text-[10px] font-semibold">
          <span className="text-up">BID {totalBid}</span>
          <span className="text-down">{totalAsk} ASK</span>
        </div>
        <div className="flex h-1.5 overflow-hidden rounded-full bg-down/70">
          <div className="h-full bg-up/70" style={{ width: `${imbalance}%` }} />
        </div>
      </div>

      <p className="border-t border-border px-4 py-2 text-[10px] leading-4 text-muted-foreground">
        Synthetic book derived from the deterministic engine — display only,
        never used for fills.
      </p>
    </div>
  );
}
